Enforce NumPy array use in Turbine utility functions
rafmudaf/floris pull request #6
Opened 2021-10-22 23:43 UTC by rafmudaf

@bayc @RHammond2 This pull request is building out the design we discussed. It's a work in progress, at the moment, but I wanted to share.

Update Oct 25: All the functions are updated to require array inputs and the unit tests are updating accordingly. I think this is much simpler and more consistent. @RHammond2 could you evaluate and review this design?

Dependencies
- #7

2021-10-25 15:53 UTC, rafmudaf commented
Well these tests pass on my computer but fail on GH :(

2021-10-26 17:58 UTC, rafmudaf commented
I've changed the setting for line length in Black to 120 characters so as to avoid chopping so many lines of code. This is also the default.

@bayc @RHammond2 Is this offensive to you?

2021-10-26 20:25 UTC, RHammond2 requested changes
Overall, this is a pretty big step in the right direction. There are a couple places for more discussion, but I think aside from a handful of small edits this is good to go because we're taking a more iterative approach to adding in functionality.

The changes I'd recommend (see review comments):
 - fixing up the couple of list comprehensions I called out
 - running the pre-commit hook over all the changed files (there are a number of formatting oddities)
   - if there are some places that you'd like to do more cherry picking with black, you could run `black --diff <file>` and copy the changes you want, and then run `SKIP=black git commit -m ...` (I'm thinking some of the inline comments that go past the line length would be annoying to have the code continue onto multiple lines)

Not needed for now, but to keep in mind as we move forward:
 - there is a good amount of functionality lacking tests, so it'd be good to get that covered
 - handling wind directions and the 5D arrays more effectively

2021-10-26 20:25 UTC, RHammond2 commented on src/turbine.py
> +    sample_arg: np.ndarray
I believe that `black` will autoformat this back to the version you switched it from, but I know this is the style we'd discussed and desired. So I would just update these two lines as such:
```python
    ix_filter: Union[List[Union[int, bool]], np.ndarray],  # fmt: off
    sample_arg: np.ndarray,  # fmt: off
```

2021-10-26 20:25 UTC, RHammond2 commented on src/turbine.py
> +) -> np.ndarray:  # (wind directions, wind speeds, turbines)
In the next set of iterations, we should incorporate these inline comments to be a part of the docstrings that had been put together in my branch so that this is easier to access for users.

2021-10-26 20:25 UTC, RHammond2 commented on src/turbine.py
>  def _filter_convert(
With the expansion to now wind directions and wind speeds, this is going to need some additional control flow, or at least it relies on the assumption that the structure of the `ix_filter` will be correct for the appropriate axis. That said, I believe we spoke about having me work on that once this PR is complete, but just want to be sure.

2021-10-26 20:25 UTC, RHammond2 commented on src/turbine.py
> +        power_interp = power_interp[:, ix_filter]
So if you expand the `turbine_unit_test.py:test_power()` to have a case where no `ix_filter` argument is passed, then this usage fails because our methodology on how to use it has failed. I left a comment about this up top, but I think if we even change the `ix_filter` argument name to `turbine_ix_filter`, and slightly modify the `_filter_convert()` function this could be correct and let us modify later.

2021-10-26 20:25 UTC, RHammond2 commented on src/turbine.py
> +        power_interp = power_interp[:, ix_filter]
I'm going to not comment on this feature in the other functions to avoid confusion/redundancy.

2021-10-26 20:25 UTC, RHammond2 commented on src/turbine.py
> +    n_turbines = np.shape(yaw_angle)[1]
This could be rewritten to the below to make it more succinct because `yaw_angle` is supposed to be an array:
```python
n_wind_speeds, n_turbines, *_ = yaw_angle.shape
```

2021-10-26 20:25 UTC, RHammond2 commented on src/turbine.py
> +
We could remove the for loops and make it a list comprehension like the following (tests pass too):
```python
    p = [
        [power_interp[i, j](yaw_effective_velocity[i, j]) for j in range(n_turbines)]
        for i in range(n_wind_speeds)
    ]
    return np.array(p) * air_density
```

2021-10-26 20:25 UTC, RHammond2 commented on src/turbine.py
> +    n_turbines = np.shape(yaw_angle)[1]
Same comment as in `power()`

2021-10-26 20:25 UTC, RHammond2 commented on src/turbine.py
> +            thrust_coefficient[i, j] = _fCt(average_velocities[i, j])
Similar to the list comprehension in `power()`:
```python
    thrust_coefficient = [
        [fCt[i, j](average_velocities[i, j]) for j in range(n_turbines)]
        for i in range(n_wind_speeds)
    ]
    effective_thrust = np.array(thrust_coefficient) * cosd(yaw_angle)
```

2021-10-26 20:25 UTC, RHammond2 commented on src/turbine.py
> +    thrust_coefficient = Ct(velocities, yaw_angle, fCt, ix_filter)
Makes so much more sense!

2021-10-26 20:25 UTC, RHammond2 commented on src/turbine.py
> +    # TODO: How to handle duplicate entries for a single wind speed?
Would this be for data validation? Is this common, and should there be a standard way of handling that, or just raise an error? This could be saved for our next meeting too.

2021-10-26 20:25 UTC, RHammond2 commented on src/turbine.py
> +        return self.fCt_interp(at_wind_speed)
This is much better, nice full use of `interp1d`!

2021-10-26 20:25 UTC, RHammond2 commented on src/farm.py
> +    def set_yaw_angles(self, yaw_angles: np.ndarray) -> None:
I'm slightly confused about the use case on this method, but it seems like `FarmController` might be of use in a later PR, so this could be ignored too.

2021-10-26 20:25 UTC, RHammond2 commented on src/farm.py
>  class Farm:
A lot of this class could be simplified through an attrs routine, but I think that's also the next PR in the lineup.

2021-10-26 20:25 UTC, RHammond2 commented on src/flow_field.py
> +        n_elements = np.prod([d for d in np.shape(grid.z[0])])                  # find the total number of elements in lower dimensions for each wind speed
This is simply: `n_elements = grid.z[0].size`.

2021-10-26 20:25 UTC, RHammond2 commented on src/wake_deflection/jimenez.py
> +        yYaw_init = ( xi_init * A / B) - ( C / D )
I agree that this is infinitely more legible, my only question is whether this adds any significant overhead or time to the calculation. That said, if it's not much, I think this format is preferred so it can be more easily followed

2021-10-26 20:25 UTC, RHammond2 commented on src/grid.py
> +        self.x = tmpx
There is in fact almost always a numpy method!
```python
self.x = np.resize(self.x, (n_wind_speeds, *self.x.shape))
```

2021-10-26 20:25 UTC, RHammond2 commented on src/grid.py
> +    def expand_wind_speed(self, n_wind_speeds):
It doesn't look like there is a test for this, but I assume here, that we're making `n_wind_speeds` copies of `self.x` for each wind speed.

2021-10-26 20:25 UTC, RHammond2 commented on src/solver.py
> +    grid.expand_wind_speed(flow_field.n_wind_speeds)
Will this be reused for wind directions also? If so, we might rename this to be more versatile, but that could wait for when wind directions are added in also.

2021-10-26 20:29 UTC, RHammond2 commented
@rafmudaf, I'd push back on the 120 line length, but would be open to 100 character line lengths. I assume this is in relation to some of the comments pushing code onto multiple lines, in which case I'm open to other ways around this because I agree that's an annoying feature when trying to have good inline documentation.

2021-10-26 21:58 UTC, rafmudaf commented on src/turbine.py
> +    # TODO: How to handle duplicate entries for a single wind speed?
I'm not sure how common this would be. If it happens, its more than likely an accident. My thought is that if its simple to handle in the code in order to save users (also ourselves) some time, let's do it. But if an appropriate response to this situation is complicated, let's leave it for the user. I'm fine with raising an error.

2021-10-26 22:00 UTC, rafmudaf commented on src/turbine.py
> +    sample_arg: np.ndarray
You're right, I let Black change it back.

2021-10-26 22:01 UTC, rafmudaf commented on src/turbine.py
> +) -> np.ndarray:  # (wind directions, wind speeds, turbines)
Agreed. I'd like to merge your work into `redesign` and then update this branch with that one.

2021-10-26 22:06 UTC, rafmudaf commented on src/turbine.py
> +        power_interp = power_interp[:, ix_filter]
[This test](https://github.com/rafmudaf/floris/blob/v3/arrays/tests/turbine_unit_test.py#L241) uses the `power` function with no `ix_filter`, and there's a corresponding case for each of these four functions. The assumption I made is that the input qualities (velocity, etc) are always the full arrays of shape (n wind speeds, n turbines, grid x, grid y). Does this cover your comment?

2021-10-26 22:18 UTC, rafmudaf commented on src/grid.py
> +    def expand_wind_speed(self, n_wind_speeds):
The lines below do that. I had initially taken your suggestion to use reshape, but it looks like it's not exactly equivalent. Good point that there's no test, I'll add that.

2021-10-26 22:21 UTC, rafmudaf commented on src/turbine.py
>  def _filter_convert(
I see what you're pointing out now. This line
```python
        return np.ones(sample_arg.shape[0], dtype=bool)
```
is specific to the data structure prior to this pull request.

2021-10-26 22:23 UTC, rafmudaf commented on src/turbine.py
> +
In my opinion, the stacked list comprehension is far less readable than the for-loops. Since we create the array prior to the loop and assign values to each element, we avoid the typical problem of appending to a Python list. That being said, I'm still adjusting my brain to look at Python code differently so maybe give me a few hours ;)

2021-10-26 22:25 UTC, rafmudaf commented on src/farm.py
> +    def set_yaw_angles(self, yaw_angles: np.ndarray) -> None:
It may be over engineering, but I thought this could be handy to operate on a single class for controls rather than stuff this into the Farm class. I'm not sure how it will be used going forward, but I could imagine some functionality built into this class or a user-defined sub class that implements some control strategies.

2021-10-26 22:25 UTC, rafmudaf commented on src/farm.py
>  class Farm:
Good call. I may add that in here, so leaving this comment unresolved.

2021-10-26 22:27 UTC, rafmudaf commented on src/wake_deflection/jimenez.py
> +        yYaw_init = ( xi_init * A / B) - ( C / D )
Good point on the performance question. I've always had a hard time reading that long equation, so my vote is to take the performance hit and get the readability. I'll leave this unresolved so we can chat about it later.

2021-10-26 22:30 UTC, rafmudaf commented on src/solver.py
> +    grid.expand_wind_speed(flow_field.n_wind_speeds)
I was thinking to have another similar function for wind direction, but I also hadn't thought that part through very much. Generally, I don't really like this pattern of expanding the grid after its created. It leaves too much room for error and smells like a hack. Some alternatives I considered:
- Pass the wind rose information into the grid and create the arrays the correct size initially. This seems like crossing the scope boundary.
- Leave the grids as they were and have another container-object handle the grid arrays for each atmospheric condition

2021-10-26 22:41 UTC, rafmudaf commented
> @rafmudaf, I'd push back on the 120 line length, but would be open to 100 character line lengths. I assume this is in relation to some of the comments pushing code onto multiple lines, in which case I'm open to other ways around this because I agree that's an annoying feature when trying to have good inline documentation.

It's driven both by comments being chopped and lines of code that are reasonably short but indented over so then they're put into a funny format. Generally, I'd like to find a way to have the automated formatting driven by content as well as line length. For example, I personally prefer this:
```python
def function__call(
    arg1: int,
    arg2arg2: float,
    arg3arg3arg3: MyObj,
) -> np.array

a = function_call(
    arg1,
    arg2arg2,
    arg3arg3arg3,
)
```
over this
```python
function_call(arg1: int, arg2arg2: float, arg3arg3arg3: MyObj) -> np.array

a = function_call(arg1, arg2arg2, arg3arg3arg3)
```
But Black makes the decision solely as a function of the length of the line. So sometimes it's the first way and other times it's the second way. I'd be happiest if we could configure it to do the same thing every time even if the result is more line of code. There are multiple benefits of the first:
- Less happening in one place
- You can easily comment arguments out during development
- Able to comment individual arguments directly

As an aside, I think what we have an aversion to is code density or complexity density. More lines of code is fine with today's IDE's. It's generally better to have every type of code block have the same format rather than optimizing our line length. Ok, done ranting.

2021-10-26 23:00 UTC, RHammond2 commented on src/turbine.py
>  def _filter_convert(
More or less, basically, this operates differently now with the expansion of the dimensions. That said, I don't think this necessarily needs to be resolved in this PR based on our discussion the other day.

2021-10-26 23:05 UTC, RHammond2 commented on src/turbine.py
> +        power_interp = power_interp[:, ix_filter]
The use case that I used it with was from [here](https://github.com/rafmudaf/floris/blob/e539f7243a1a07b967a1afa2fd71f12dc3884d0c/tests/turbine_unit_test.py#L254-L261), but removing the `ix_filter` argument. I think the one you're pointing to is adequate if we don't have values in the expanded dimensions, but once you do, then the `_filter_convert()` function ends up producing incorrect results.

I think  this is also part of the above comment for us to be aware of now that we're expanding to the full 5 dimensions, so it doesn't need to be resolved here because I more or less wanted to call it out specifically.

2021-10-26 23:07 UTC, RHammond2 commented on src/turbine.py
> +
It can definitely be weird to look at initially. We could also create variables for the two ranges and I believe that'd keep the comprehension all on one line.

2021-10-26 23:08 UTC, RHammond2 commented on src/turbine.py
> +    # TODO: How to handle duplicate entries for a single wind speed?
I'll note this to be included once this PR and PR #7 are complete, but I think it should be fairly straightforward as a post-init validation step.

2021-10-26 23:09 UTC, RHammond2 commented on src/farm.py
> +    def set_yaw_angles(self, yaw_angles: np.ndarray) -> None:
Let's just keep it as is then!

2021-10-26 23:22 UTC, RHammond2 commented on src/solver.py
> +    grid.expand_wind_speed(flow_field.n_wind_speeds)
I'm fine with this as-is for the time being, but I think this is a really great design question that we're getting into for expansion without scope creep. It's totally possible this pattern is also how we'd want it to avoid more code in other places as well. My one other thought would be something like:
```python
def expand_grid(*args):
    """The *args should be any dimensions you want added, from innermost to outermost"""
    for dim_size in args:
        tmpx = np.zeros( (n_wind_speeds, *np.shape(self.x)) )
        tmpx[:] = self.x
        self.x = tmpx
        # the other attributes
```
which could be used in a pattern similar to the following two styles:
```python
# 1
grid.expand_grid(self.n_wind_speeds, self.n_wind_directions)
```
```python
# 2
grid.expand_grid(self.n_wind_speeds)
grid.expand_grid(self.n_wind_directions)
```

2021-10-26 23:31 UTC, RHammond2 commented
I agree on the styling difference, especially with the usage of type hints, but I don't know of an automated way to perform that customization at the moment, at least not with black. Though there are other formatters we could take for a spin that offer more customization.

The current solution would be to put `# fmt: off` at the end of the line, though this won't work if you're making an inline comment. That said, that's a really dissatisfying fix because it will ignore all possible errors that could be happening.

2021-10-26 23:45 UTC, RHammond2 commented on src/grid.py
> +    def expand_wind_speed(self, n_wind_speeds):
For my own future reference, what was the differing behavior? It seems like I didn't quite understand the use case.

2021-10-28 19:41 UTC, rafmudaf commented
> The current solution would be to put `# fmt: off` at the end of the line, though this won't work if you're making an inline comment. That said, that's a really dissatisfying fix because it will ignore all possible errors that could be happening.

Agreed. This also adds more noise to the code which is against the intention of cleaning up the code to make it easier on the eyes.

2021-11-01 14:50 UTC, merged